config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"
  get '/about' => 'public/homes#about'
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_for :admin, skip:[:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  scope module: :public do
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end

    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end

    resources :addresses, only: [:index, :edit, :create, :update, :destroy] do
    end

    get '/customers/my_page' => 'customers#show'
    get '/customers/my_page/edit' => 'customers#edit'
    patch '/customers/my_page' =>'customers#update'
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw'

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    root to: "homes#top"
    resources :orders, only:[:show, :update]
    resources :order_details, only:[:update]
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  validates :amount, presence: true

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items
  has_many :orders
  has_many :addresses

  def full_name
    last_name + "　" + first_name
  end

  def full_name_kana
    last_name_kana + "  " + first_name_kana
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details
  attachment :image

  def get_image
    image
  end

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait: 0, confirm: 1, make: 2, radytoship: 3, shipped: 4}
  belongs_to :customer
  has_many :order_details

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum making_status: { donotmade: 0, wait: 1, make: 2, finish: 3}
  belongs_to :order
  belongs_to :item

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    before_action :authenticate_admin!

    def index
        @genres = Genre.all
        @genre = Genre.new
    end
    def create
        genre = Genre.new(genre_params)
        genre.save
        redirect_to admin_genres_path
    end
    def edit
        @genre = Genre.find(params[:id])
    end
    def update
        genre = Genre.find(params[:id])
        genre.update(genre_params)
        redirect_to admin_genres_path
    end
    private

    def genre_params
        params.require(:genre).permit(:name)
    end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders= Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @item = Item.new
  end

  def create
    @item = Item.new
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def index
    @items = Item.all
  end
  def show
    @item = Item.find(params[:id])
  end
  def edit
    @item = Item.find(params[:id])
  end
  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_items_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :is_active, :genre_id)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def show
    @order = Order.find(params[:id])
    @total = 0
  end

  def update
    order = Order.find(params[:id]) #注文詳細の特定
    order.update(order_params) #注文ステータスの更新
    # byebug
    if order.status == "confirm" #もしステータスが入金確認だったら
      order.order_details.update_all(making_status: 1)#order_ditailのmaking_statusすべて1にこうしん。
    end

    redirect_to admin_order_path(order.id)
  end

  private
  def order_params
    params.require(:order).permit(:status)
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <h4>ジャンル編集</h4>
  <div class="row">
    <%= form_with model: @genre, url: admin_genre_path, method: :patch do |f| %>
    <table class="table table-borderless">
      <tr>
        <th>ジャンル名</th>
        <td>
          <%= f.text_field :name %>
          <%= f.submit '変更を保存', class:'btn btn-success' %>
        </td>
      </tr>
    </table>
    <% end %>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <h4>ジャンル一覧・追加</h4>
  <div class="row">
    <%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
    <table class="table table-borderless">
      <tr>
        <th>ジャンル名</th>
        <td>
          <%= f.text_field :name %>
          <%= f.submit '新規投稿', class:'btn btn-success' %>
        </td>
      </tr>
    </table>
  </div>
    <% end %>
    <h4>ジャンル</h4>
  <div class="row">
    <table class="table table-borderless col-sm-5">
      <% @genres.each do |genre| %>
      <tr>
        <th><%= genre.name %></th>
        <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class:'btn btn-primary' %></td>
      </tr>
      <% end %>
    </table>
  </div>

</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <h2>商品編集</h2>
  <div class="row">
    <%= form_with model: @item, url: admin_item_path, method: :patch do |f| %>
    <table class="table table-borderless">
      <tr>
        <th>商品画像</th>
        <td><%= f.attachment_field :image %></td>
      </tr>
      <tr>
        <th>商品名</th>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <th>商品説明</th>
        <td><%= f.text_area :introduction %></td>
      </tr>
      <tr>
        <th>ジャンル</th>
        <td><%= f.collection_select :genre_id, Genre.all,  :id, :name  %></td>
      </tr>
      <tr>
        <th>税抜価格</th>
        <td><%= f.text_field :price %></td>
      </tr>
      <tr>
        <th>販売ステータス</th>
        <td>
          <%= f.radio_button :is_active, true %>
          <%= f.label :is_active, '販売中', value: true %>
          <%= f.radio_button :is_active, false %>
          <%= f.label :is_active, '販売停止中', value: false %><br>
           
        </td>
      </tr>
    </table>
    <%= f.submit '変更を保存' ,class:'btn btn-success'%>  
    <% end %>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <h2 class="col-5">商品一覧</h2>
    <div class="btn btn-light rounded-circle p-0 ml-auto" style="width:2rem;height:2rem;">
      <%= link_to "+", new_admin_item_path %>
    </div>
   
    <table class="table table-borderless">
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
      </tr>
      <% @items.each do |item| %>
      <tr>
        <td>
          <%= item.id %>
        </td>
        <td><%= link_to item.name, admin_item_path(item.id) %></td>
        <td><%= item.price %></td>
        <td><%= item.genre.name %></td>
        <td><%= item.is_active ? '販売中' : '販売停止中' %></td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <h2>商品新規登録</h2>
  <div class="row">
    <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
    <table class="table table-borderless col-sm-12">
      <tr>
        <th>商品画像</th>
        <td><%= f.attachment_field :image %></td>
      </tr>
      <tr>
        <th>商品名</th>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <th>商品説明</th>
        <td><%= f.text_area :introduction %></td>
      </tr>
      <tr>
        <th>ジャンル</th>
        <td><%= f.collection_select :genre_id, Genre.all,  :id, :name  %></td>
      </tr>
      <tr>
        <th>税抜価格</th>
        <td><%= f.text_field :price %></td>
      </tr>
      <tr>
        <th>販売ステータス</th>
        <td>
          <%= f.radio_button :is_active, true %>
          <%= f.label :is_active, '販売中', value: true %>
          <%= f.radio_button :is_active, false %>
          <%= f.label :is_active, '販売停止中', value: false %><br>
        </td>
      </tr>
    </table>
    <%= f.submit '新規登録', class:'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <h2>商品詳細</h2>
  <div class="row">
    <%= attachment_image_tag @item, :image, format: 'jpeg', size: '400x300',class:'col-sm-5' %>
    <table class="table table-borderless col-sm-7">
      <tr><th>商品名</th><td><%= @item.name %></td></tr>
      <tr><th>商品説明</th><td><%= @item.introduction %></td></tr>
      <tr><th>ジャンル</th><td><%= @item.genre.name %></td></tr>
      <tr><th>税込価格<br>(税抜価格)</th><td>
        <% tax = (@item.price * 1.1).floor.to_s(:delimited) %>
        <%= tax %>(<%= @item.price.to_s(:delimited) %>)円
      </td></tr>
      <tr><th>販売ステータス</th><td><%= @item.is_active ? '販売中' : '販売停止中' %></td></tr>
    </table>
    <%= link_to "編集する", edit_admin_item_path(@item.id), class:'btn btn-success mx-auto mt-2' %>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <h4>注文履歴詳細</h4>
    <table class="table table-borderless">
      <tr><th>購入者</th><td><%= @order.customer.full_name %></td></tr>
      <tr><th>注文日</th><td><%= @order.created_at.to_s(:datetime_jp) %></td></tr>
      <tr><th>配送先</th><td>〒<%= @order.postal_code %><%= @order.address %> <br><%= @order.name %></td></tr>
      <tr><th>支払方法</th><td><%= @order.payment_method_i18n %></td></tr>
      <tr><th>注文ステータス</th>
        <td>
          <%= form_with model: @order, url: admin_order_path, method: :patch do |f| %>
          <%= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enums.order.status.#{k}"), k]} %>
          <%= f.submit "更新" %>
          <% end %>
        </td></tr>
    </table>
    <table class="table table-striped col-sm-8">
      <tr>
        <th>商品名</th>
        <th>単価(税込)</th>
        <th>個数</th>
        <th>小計</th>
        <th></th>
      </tr>
      <% @order.order_details.each do |order_detail| %>
      <tr>
        <td><%= order_detail.item.name %></td>
        <td><%= order_detail.item.with_tax_price %></td>
        <td><%= order_detail.amount %></td>
        <td><%= (order_detail.item.with_tax_price * order_detail.amount).to_s(:delimited) %></td>
        <td>
          <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id), method: :patch do |f| %>
          <%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %>
          <%= f.submit "更新" %>
          <% end %>
        </td>
      </tr>
      <% @total += (order_detail.item.with_tax_price * order_detail.amount) %>
      <% end %>
    </table>
    <table class=" col-sm-3 offset-sm-1">
      <tr><th>商品合計</th><td><%= @total.to_s(:delimited) %></td></tr>
      <tr><th>送料</th><td><%= @order.shipping_cost %></td></tr>
      <% @total_payment= @total + @order.shipping_cost %>
      <tr><th>請求金額</th><td><%= total_payment = @total_payment.to_s(:delimited) %></td></tr>
    </table>
  </div>

</div>