config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"
  get '/about' => 'public/homes#about'
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_for :admin, skip:[:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  scope module: :public do
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end

    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        post 'confirm'
        get 'complete'
      end
    end

    resources :addresses, only: [:index, :edit, :create, :update, :destroy] do
    end

    get '/customers/my_page' => 'customers#show'
    get '/customers/my_page/edit' => 'customers#edit'
    patch '/customers/my_page' =>'customers#update'
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdraw' => 'customers#withdraw'

  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    root to: "homes#top"
    resources :orders, only:[:show, :update]
    resources :order_details, only:[:update]
  end

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer
  
  validates :amount, presence: true

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items
  has_many :orders
  has_many :addresses

  def full_name
    last_name + "　" + first_name
  end

  def full_name_kana
    last_name_kana + "  " + first_name_kana
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items
  has_many :order_details
  attachment :image

  def get_image
    image
  end

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait: 0, confirm: 1, make: 2, radytoship: 3, shipped: 4}
  belongs_to :customer
  has_many :order_details

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum making_status: { donotmade: 0, wait: 1, make: 2, finish: 3}
  belongs_to :order
  belongs_to :item

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    before_action :authenticate_admin!

    def index
        @genres = Genre.all
        @genre = Genre.new
    end
    def create
        genre = Genre.new(genre_params)
        genre.save
        redirect_to admin_genres_path
    end
    def edit
        @genre = Genre.find(params[:id])
    end
    def update
        genre = Genre.find(params[:id])
        genre.update(genre_params)
        redirect_to admin_genres_path
    end
    private

    def genre_params
        params.require(:genre).permit(:name)
    end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders= Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @item = Item.new
  end

  def create
    @item = Item.new
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def index
    @items = Item.all
  end
  def show
    @item = Item.find(params[:id])
  end
  def edit
    @item = Item.find(params[:id])
  end
  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_items_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :is_active, :genre_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body >
    <header class= >
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class= "navbar-brand" href="/">
    <%= image_tag "img2.JPG" %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <!--会員でログイン時-->
      <% if customer_signed_in? %>
      <li class="nav-itme">ようこそ、<%= current_customer.last_name %>さん！</li>
      <li class="nav-item ml-5">
        <button type="button" class="btn btn-outline-primary btn-sm"> <%= link_to "マイページ", customers_my_page_path %></button>
      </li>
      <li class="nav-item ml-5">
        <button type="button" class="btn btn-outline-primary btn-sm"> <%= link_to "商品一覧", items_path %> </button>
      </li>
      <li class="nav-item ml-5">
        <button type="button" class="btn btn-outline-primary btn-sm"> <%= link_to "カート", cart_items_path %> </button>
      </li>
      <li class="nav-item ml-5 mr-5">
        <button type="button" class="btn btn-outline-primary btn-sm"> <%= link_to "ログアウト", destroy_customer_session_path, method: :delete %> </button>
      </li>
      <!--管理者でログイン時-->
      <% elsif admin_signed_in? %>
      <li class="nav-item">
        <button type="button" class="btn btn-outline-primary btn-sm"> <%= link_to "商品一覧", admin_items_path %></button>
      </li>
      <li class="nav-item ml-5">
        <button type="button" class="btn btn-outline-primary btn-sm"> <%= link_to "会員一覧", admin_customers_path %> </button>
      </li>
      <li class="nav-item ml-5">
        <button type="button" class="btn btn-outline-primary btn-sm"> <%= link_to "注文履歴一覧", admin_root_path %> </button>
      </li>
      <li class="nav-item ml-5">
        <button type="button" class="btn btn-outline-primary btn-sm"> <%= link_to "ジャンル一覧", admin_genres_path %></button>
      </li>
      <li class="nav-item ml-5 mr-5">
        <button type="button" class="btn btn-outline-primary btn-sm"> <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %> </button>
      </li>
      <!--ログイン前-->
      <% else %>
      <li class="nav-item">
        <button type="button" class="btn btn-outline-primary btn-sm"> <%= link_to "About", about_path %></button>
      </li>
      <li class="nav-item ml-5">
        <button type="button" class="btn btn-outline-primary btn-sm"> <%= link_to "商品一覧",items_path %> </button>
      </li>
      <li class="nav-item ml-5">
        <button type="button" class="btn btn-outline-primary btn-sm"> <%= link_to "新規登録", new_customer_registration_path %> </button>
      </li>
      <li class="nav-item ml-5 mr-5">
        <button type="button" class="btn btn-outline-primary btn-sm"> <%= link_to "ログイン", new_customer_session_path %></button>
      <% end %>
      </li>
    </ul>
  </div>
</nav>
    </header>
    <%= yield %>

  </body>
</html>